module.exports = {
  GET_INTRADAY: 'GET_INTRADAY',
  GET_INTRADAY_SUCCESS: 'GET_INTRADAY_SUCCESS',
  GET_INTRADAY_ERROR: 'GET_INTRADAY_ERROR',
  GET_DAILY_REPORT: 'GET_DAILY_REPORT',
  GET_DAILY_REPORT_SUCCESS: 'GET_DAILY_REPORT_SUCCESS',
  GET_DAILY_REPORT_ERROR: 'GET_DAILY_REPORT_ERROR',
  GET_SECTOR_PERFORMANCE: 'GET_SECTOR_PERFORMANCE',
  GET_SECTOR_PERFORMANCE_SUCCESS: 'GET_SECTOR_PERFORMANCE_SUCCESS',
  GET_SECTOR_PERFORMANCE_ERROR: 'GET_SECTOR_PERFORMANCE_ERROR'
};
